services:

  # It looks like variable interpolation doesn't get namespaced under the provided .env file, so we can't have both the env_file and environment options with interpolations on the latter since the variables used in the substitutions won't be sourced from the associated .env file, but rather will be sourced from the shell and *the* .env files.
  # So we have to define all the variables for the target service in their associated .env file or have prefixed versions in a single .env file. As you'll see, we went with the former approach, having separate .env files for each relevant service, though this means the ports need to be hardcoded.
  # Changes to the port must be propagated to the justfile and the associated .env file for that service. A tradeoff, but it keeps things more organized and modular, which is nice.
  db:
    image: postgres:16
    container_name: village_database
    env_file:
      - path: ./backend/.env
        required: true
      - path: ./backend/.env.dev
        required: false
    ports:
      - "5432:5432"
    volumes:
      # We are saying the docker volume "postgres-data" should be mounted at the path "/var/lib/postgresql/data" in the container. This is where our postgres data will be stored. By using a volume, we ensure that our data persists across container restarts and removals. Something to note, the path "/var/lib/postgresql/data" is the default data directory for PostgreSQL in the official Docker image.
      - postgres_data:/var/lib/postgresql/data

  # This way we can have a separate db for automated testing that won't be affected by any of the manual stuff we do with the main db. We can also run them at the same time if we want to, which is nice.
  test_db:
    image: postgres:16
    container_name: village_test_database
    env_file:
      - path: ./backend/.env.test
        required: true
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data: # Here we are declaring the volume for our postgres (the main_db) service. It looks empty but all we're doing is registering the volume name. Docker handles the rest from there
  postgres_test_data: # Here we are declaring the volume for our postgres (the test_db) service. It looks empty but all we're doing is registering the volume name. Docker handles the rest from there
